name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{vars.Version}} 

    steps:
    - name: 显示环境变量
      run: ${{env.VERSION}} = 3

    - name: 显示变量
      run: echo ${{env.VERSION}}
        
